# Clojure CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.5 
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      DOCKER_IMAGE: "agranado2k/pipeline-test"
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      # install npm packages
      - run: sudo apt update && sudo apt install nodejs npm && npm install
      # run lint
      - run: lein eastwood
      # run tests
      - run: lein test
      - run: ./scripts/build-push-image.sh "$DOCKER_IMAGE" "$CIRCLE_SHA1"
      - run: TAG=$(scripts/get-git-label-version.sh "$CIRCLE_SHA1") && DOCKER_TAG="${TAG}"
      - run: echo "DOCKER_TAG=${DOCKER_TAG}"
      
workflows:
  version: 2
  build_and_deployment:
    jobs:
      - build